import { jsPDF } from 'jspdf'
import { resolutionToMP } from '../services/scanService.js'

function fmtDate(d) {
  if (!d) return ''
  return new Date(d).toLocaleString('en-IN', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' })
}

export function generatePDF(certificate) {
  if (!certificate) return
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210, margin = 18, cW = 210 - 36
  let y = 0

  // Header
  doc.setFillColor(24, 119, 200)
  doc.rect(0, 0, W, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18); doc.setFont('helvetica','bold')
  doc.text('HakkiEye', margin, 12)
  doc.setFontSize(10); doc.setFont('helvetica','normal')
  doc.text('Installation Scan Certificate', margin, 21)
  y = 38

  // Meta
  doc.setTextColor(26, 25, 23); doc.setFontSize(9)
  doc.setFont('helvetica','bold'); doc.text('Certificate ID', margin, y)
  doc.setFont('helvetica','normal'); doc.text(certificate.id || '—', margin+36, y); y+=6
  doc.setFont('helvetica','bold'); doc.text('Date', margin, y)
  doc.setFont('helvetica','normal'); doc.text(fmtDate(certificate.generatedAt), margin+36, y); y+=6
  if (certificate.protocol) {
    doc.setFont('helvetica','bold'); doc.text('Protocol', margin, y)
    doc.setFont('helvetica','normal'); doc.text(certificate.protocol.toUpperCase(), margin+36, y); y+=6
  }
  y += 4

  // Device info
  const di = certificate.deviceInfo
  if (di) {
    doc.setFillColor(241,239,232); doc.rect(margin, y, cW, 16, 'F')
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.text('DEVICE', margin+3, y+5)
    doc.setFont('helvetica','normal')
    if (di.model)         doc.text(`Model: ${di.model}`, margin+3, y+10)
    if (di.serialNumber)  doc.text(`Serial: ${di.serialNumber}`, margin+3+cW/2, y+10)
    if (di.firmwareVersion) doc.text(`Firmware: ${di.firmwareVersion}`, margin+3, y+15)
    y += 22
  }

  // Cameras table
  if (certificate.cameras?.length) {
    doc.setFont('helvetica','bold'); doc.setFontSize(10); doc.setTextColor(26,25,23)
    doc.text('Cameras', margin, y); y+=6
    doc.setFillColor(241,239,232); doc.rect(margin, y, cW, 7, 'F')
    doc.setFontSize(8)
    const cols = [margin, margin+15, margin+60, margin+110, margin+135]
    doc.text('CH', cols[0]+2, y+5); doc.text('Name', cols[1]+2, y+5)
    doc.text('Resolution', cols[2]+2, y+5); doc.text('MP', cols[3]+2, y+5)
    doc.text('Status', cols[4]+2, y+5); y+=9
    doc.setFont('helvetica','normal')
    certificate.cameras.forEach((cam, i) => {
      if (i%2===0) { doc.setFillColor(249,248,245); doc.rect(margin, y, cW, 7, 'F') }
      doc.setTextColor(26,25,23)
      doc.text(`${cam.channelId}`, cols[0]+2, y+5)
      doc.text(doc.splitTextToSize(cam.name||'—', 42), cols[1]+2, y+5)
      doc.text(cam.resolution||'—', cols[2]+2, y+5)
      const mp = cam.mp ?? resolutionToMP(cam.resolution)
      doc.text(mp!=null?`${mp}`:' —', cols[3]+2, y+5)
      doc.text(cam.status||'—', cols[4]+2, y+5)
      y+=7
    }); y+=5
  }

  // Storage table
  if (certificate.storage?.length) {
    doc.setFont('helvetica','bold'); doc.setFontSize(10); doc.setTextColor(26,25,23)
    doc.text('Storage', margin, y); y+=6
    doc.setFillColor(241,239,232); doc.rect(margin, y, cW, 7, 'F')
    doc.setFontSize(8)
    doc.text('#', margin+2, y+5); doc.text('Type', margin+15, y+5)
    doc.text('Size', margin+50, y+5); doc.text('Status', margin+90, y+5); y+=9
    doc.setFont('helvetica','normal')
    certificate.storage.forEach((d, i) => {
      if (i%2===0) { doc.setFillColor(249,248,245); doc.rect(margin, y, cW, 7, 'F') }
      doc.setTextColor(26,25,23)
      doc.text(`${d.id||i+1}`, margin+2, y+5)
      doc.text(d.type||'HDD', margin+15, y+5)
      doc.text(d.totalGB!=null?`${d.totalGB} GB`:'—', margin+50, y+5)
      doc.text(d.status||'—', margin+90, y+5)
      y+=7
    }); y+=5
  }

  // Disclaimer
  y+=4
  doc.setFillColor(245,244,241); doc.setDrawColor(200,196,188)
  const disclaimerLines = doc.splitTextToSize(certificate.disclaimer||'', cW-8)
  const boxH = 10 + disclaimerLines.length * 4
  doc.roundedRect(margin, y, cW, boxH, 3, 3, 'FD')
  doc.setTextColor(107,104,96); doc.setFontSize(8); doc.setFont('helvetica','bold')
  doc.text('Disclaimer', margin+4, y+7)
  doc.setFont('helvetica','normal')
  doc.text(disclaimerLines, margin+4, y+12)
  y += boxH + 6

  // Footer
  doc.setFillColor(24,119,200); doc.rect(0,287,W,10,'F')
  doc.setTextColor(255,255,255); doc.setFontSize(8)
  doc.text('Generated by HakkiEye — hakki.app | Free, open source, no credentials stored', W/2, 293, {align:'center'})

  doc.save(`HakkiEye-${certificate.id}.pdf`)
}
